### ISSUE TITLE
New ASoftmax implementation

### ISSUE THREAD

**Issue by ozora-ogino** [4uiiurz1/keras-arcface#29]
Hi there,

In this repository, ArcFace and others have some issues such as passing label to model is needed when prediction.
So I implemented new one.

https://github.com/ozora-ogino/asoftmax-tf

This can help your problem and you don't need to pass labels to model in prediction anymore.

Thank you.

**Comment by sauravsolanki** [comment]
hi @ozora-ogino , your implementation is totaly wrong. This is misleading. Find out real answer here: https://github.com/deepinsight/insightface/blob/78316896468ecd4f929b1ef8b117d0ea7fa3f821/recognition/arcface_paddle/test_recognition.py#L642

**Comment by ozora-ogino** [comment]
@sauravsolanki I'm so sorry about that...
Thank you for sharing the information and let me correct it.
